const state_map = {
  "Maharashtra": "MH",
  "Andhra Pradesh": "AP",
  "Karnataka": "KA",
  "Tamil Nadu": "TN",
  "Uttar Pradesh": "UP",
  "Delhi": "DL",
  "Kerala": "KL",
  "West Bengal": "WB",
  "Odisha": "OR",
  "Telangana": "TG",
  "Bihar": "BR",
  "Assam": "AS",
  "Rajasthan": "RJ",
  "Gujarat": "GJ",
  "Madhya Pradesh": "MP",
  "Chattisgarh": "CT",
  "Haryana": "HR",
  "Punjab": "PB",
  "Jharkhand": "JH",
  "Jammu and Kashmir": "JK",
  "Uttarakhand": "UT",
  "Goa": "GA",
  "Puducherry": "PY",
  "Tripura": "TR",
  "Himachal Pradesh": "HP",
  "Manipur": "MN",
  "Chandigarh": "CH",
  "Arunachal Pradesh": "AR",
  "Meghalaya": "ML",
  "Nagaland": "NL",
  "Ladakh": "LA",
  "Andaman and Nicobar Islands": "AN",
  "Sikkim": "SK",
  "Dadra and Nagar Haveli and Daman and Diu": "DN",
  "Mizoram": "MZ",
  "Lakshwadeep": "LD",
};
